# Generated by Django 5.0.1 on 2024-01-06 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0003_play_acts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="artist",
            new_name="artists",
        ),
        migrations.RenameField(
            model_name="play",
            old_name="genre",
            new_name="genres",
        ),
    ]
