# Generated by Django 5.0.1 on 2024-01-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0004_rename_artist_play_artists_rename_genre_play_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
