# Generated by Django 5.0.1 on 2024-01-06 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0005_artist_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={
                "ordering": ("title",),
                "verbose_name": "play",
                "verbose_name_plural": "plays",
            },
        ),
    ]
