# Generated by Django 5.0.1 on 2024-01-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0006_alter_play_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="artists",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre.artist"
            ),
        ),
    ]
