# Generated by Django 5.0.1 on 2024-01-07 12:27

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0007_alter_play_artists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=theatre.models.object_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre.genre"
            ),
        ),
    ]
