# Generated by Django 5.0.1 on 2024-02-14 11:47

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0012_alter_reservation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.object_image_file_path
            ),
        ),
    ]
