# Generated by Django 5.0.1 on 2024-02-14 12:03

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0013_alter_artist_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.object_image_file_path
            ),
        ),
    ]
